src/laravelweb/routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
use App\NhanVien;

Route::get('/', function () {
    return view('welcome');
});

//Tạo route cho phép chuyển đổi ngôn ngữ
Route::get('setLocale/{locale}', function ($locale) {
    if (in_array($locale, Config::get('app.locales'))) {
      Session::put('locale', $locale);
    }
    return redirect()->back();
})->name('app.setLocale');


// route Danh mục Sản phẩm
Route::get('/admin/danhsachsanpham/index', 'SanPhamController@index')->name('danhsachsanpham.index');
Route::get('/admin/danhsachsanpham/create', 'SanPhamController@create')->name('danhsachsanpham.create');

Route::get('/admin/danhsachsanpham/print', 'SanPhamController@print')->name('danhsachsanpham.print');
Route::get('/admin/danhsachsanpham/excel', 'SanPhamController@excel')->name('danhsachsanpham.excel');

Route::resource('/admin/danhsachsanpham', 'SanPhamController');

Route::get('/admin/danhsachsanpham', 'SanPhamController@index')
        ->middleware('auth')
        ->name('backend.sanpham.index');

// route Danh mục Loại

Route::resource('/admin/danhsachloai', 'LoaiController');
//cap quyen
Route::get('/capquyen', function(){

    //user1 & user2 = ketoan
    $user1 = NhanVien::find(1);
    $user1->givePermissionTo('sp_xem');
    $user1->givePermissionTo('sp_print');
    $user1->givePermissionTo('sp_excel');

    $user1->givePermissionTo('l_xem');


    $user2 = Nhanvien::find(2);
    $user2->givePermissionTo('sp_xem');
    $user2->givePermissionTo('sp_print');
    $user2->givePermissionTo('sp_excel');

    $user2->givePermissionTo('l_xem');


    //user3 & user4 = thukho
    $user3 = Nhanvien::find(3);
    $user3->givePermissionTo('kho_xem');
    $user3->givePermissionTo('kho_them');
    $user3->givePermissionTo('kho_sua');
    $user3->givePermissionTo('kho_xoa');

    $user4 = Nhanvien::find(3);
    $user4->givePermissionTo('kho_xem');
    $user4->givePermissionTo('kho_them');
    $user4->givePermissionTo('kho_sua');
    $user4->givePermissionTo('kho_xoa');

    //user100 = admin
    $user100 = Nhanvien::find(100);
    $user100->givePermissionTo('sp_xem');
    $user100->givePermissionTo('sp_them');
    $user100->givePermissionTo('sp_sua');
    $user100->givePermissionTo('sp_xoa');
    $user100->givePermissionTo('sp_excel');
    $user100->givePermissionTo('sp_print');

    $user100->givePermissionTo('l_xem');
    $user100->givePermissionTo('l_them');
    $user100->givePermissionTo('l_sua');
    $user100->givePermissionTo('l_xoa');
    
    return 'cap quyen okey';
});

Auth::routes();
//sua
//Route::get('/login', 'HomeController@index')->name('login');
//Route::get('/login', 'Backend\BackendController')->name('login');


Route::get('/home', 'HomeController@index')->name('home');

Route::post('/admin/activate/{nv_ma}', 'Backend\BackendController@activate')->name('activate');

//Thực hiện tạo giao diện trang chủ Frontend
Route::get('/', 'Frontend\FrontendController@index')->name('frontend.home');

//Thực hiện tạo giao diện trang Giới thiệu (about)
Route::get('/gioi-thieu', 'Frontend\FrontendController@about')->name('frontend.about');

//Thực hiện tạo giao diện trang Liên hệ (contact)
Route::get('/lien-he', 'Frontend\FrontendController@contact')->name('frontend.contact');

//tạo route sendMailContactForm
Route::post('/lien-he/goi-loi-nhan', 'Frontend\FrontendController@sendMailContactForm')->name('frontend.contact.sendMailContactForm');

//Tạo trang danh sách Sản phẩm (product)
Route::get('/san-pham', 'Frontend\FrontendController@product')->name('frontend.product');

//Tạo trang Chi tiết Sản phẩm (product-detail)
Route::get('/san-pham/{id}', 'FrontendController@productDetail')->name('frontend.productDetail');

//Tạo trang thanh toán (checkout)
Route::get('/gio-hang', 'Frontend\FrontendController@cart')->name('frontend.cart');

//Tạo đơn hàng và gởi mail xác nhận
Route::get('/gio-hang', 'Frontend\FrontendController@cart')->name('frontend.cart');
Route::post('/dat-hang', 'Frontend\FrontendController@order')->name('frontend.order');
Route::get('/dat-hang/hoan-tat', 'Frontend\FrontendController@orderFinish')->name('frontend.orderFinish');

src/laravelweb/app/Loai.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Loai extends Model
{
    const     CREATED_AT    = 'l_ngaytaoMoi';
    const     UPDATED_AT    = 'l_ngaycapNhat';
    protected $table        = 'loai';
    protected $fillable     = ['l_ten', 'l_ngaytaoMoi', 'l_ngaycapNhat', 'l_trangThai'];
    protected $guarded      = ['l_ma'];
    protected $primaryKey   = 'l_ma';
    protected $dates        = ['l_ngaytaoMoi', 'l_ngaycapNhat'];
    protected $dateFormat   = 'Y-m-d H:i:s';

    public function sanpham(){
        return $this->hasMany('App\SanPham', 'l_ma', 'l_ma');
    }
}

src/laravelweb/app/Http/Controllers/Backend/BackendController.php
<?php

namespace App\Http\Controllers\Backend;

use App\Nhanvien;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class BackendController extends Controller
{
    public function activate(Request $request, $nv_ma) 
    {
        $nv = Nhanvien::find($nv_ma);
        $nv->nv_trangThai = 2; // Khả dụng
        $nv->save();
        return redirect()->route('admin/danhsachsanpham');
    }
}

src/laravelweb/app/Http/Controllers/LoaiController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

use App\Loai;
use Session;


use Illuminate\Support\Facades\Auth;
use Illuminate\Auth\Middleware\Authenticate;

class LoaiController extends Controller
{
    //
    // action
    public function show() {

       
    }
    public function index() {

        //$ds_loai = Loai::all();
        $ds_loai = Loai::paginate(3); 
        
        return view('backend.loai.index')
        ->with('danhsachloai', $ds_loai);

    }
   
    public function create()
    {
        $ds_loai = Loai::all(); // SELECT * FROM loai
        return view('backend.loai.create')
            // với dữ liệu truyền từ Controller qua View, được đặt tên là `danhsachloai`
            ->with('danhsachloai', $ds_loai);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $loai = Loai::where("l_ma",  $id)->first();;

        return view('backend.loai.edit')
            ->with('l', $loai);

            
    }

    public function update(Request $request, $id)
    {
        
        $l = Loai::where("l_ma",  $id)->first();;
        $l->l_ten = $request->l_ten;
        $l->l_ngaytaoMoi = $request->l_ngaytaoMoi;
        $l->l_ngaycapNhat = $request->l_ngaycapNhat;
        $l->l_trangThai = $request->l_trangThai;
        $l->l_ma = $request->l_ma;
        
        $l->save();

        Session::flash('alert-info', 'Cập nhật thành công ^^~!!!');
        return redirect()->route('danhsachloai.index');
    }
    public function store(Request $request)
    {
        
        $l = new Loai();
        $l->l_ten = $request->l_ten;
        $l->l_ngaytaoMoi = $request->l_ngaytaoMoi;
        $l->l_ngaycapNhat = $request->l_ngaycapNhat;
        $l->l_trangThai = $request->l_trangThai;
        $l->l_ma = $request->l_ma;
        
        $l->save();

        Session::flash('alert-info', 'Them moi thanh cong ^^~!!!');
        
        return redirect()->route('danhsachloai.index');
    }

    public function destroy($id)
    {
    $l = Loai::where("l_ma",  $id)->first();
    
    $l->delete();

    Session::flash('alert-info', 'Xóa loại sản phẩm thành công ^^~!!!');
    return redirect()->route('danhsachloai.index');
    }

   
}

src/laravelweb/resources/views/backend/loai/create.blade.php
@extends('backend.layouts.master')

    @section('title')
    Thêm mới loại sản phẩm
    @endsection

    @section('custom-css')
    <!-- Các css dành cho thư viện bootstrap-fileinput -->
    <link href="{{ asset('vendor/bootstrap-fileinput/css/fileinput.css') }}" media="all" rel="stylesheet" type="text/css"/>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.5.0/css/all.css" crossorigin="anonymous">
    <link href="{{ asset('vendor/bootstrap-fileinput/themes/explorer-fas/theme.css') }}" media="all" rel="stylesheet" type="text/css"/>
    @endsection
    

    @section('main-content')

    <!-- show lỗi sai lên màn hình nếu có -->
    @if ($errors->any())
        <div class="alert alert-danger">
            <ul>
                @foreach ($errors->all() as $error)
                    <li>{{ $error }}</li>
                @endforeach
            </ul>
        </div>
    @endif
    
    <form method="post" action="{{ route('danhsachloai.store') }}" enctype="multipart/form-data">
        {{ csrf_field() }}
       
        <div class="form-group">
            <label for="l_ten">Tên loại sản phẩm</label>
            <input type="text" class="form-control" id="l_ten" name="l_ten" value="{{ old('l_ten') }}">
        </div>
        
        <div class="form-group">
            <label for="l_ngaytaoMoi">Ngày tạo mới</label>
            <input type="date" class="form-control" id="l_ngaytaoMoi" name="l_ngaytaoMoi" value="{{ old('l_ngaytaoMoi') }}" data-mask-datetime>
        </div>
        <div class="form-group">
            <label for="l_ngaycapNhat">Ngày cập nhật</label>
            <input type="date" class="form-control" id="l_ngaycapNhat" name="l_ngaycapNhat" value="{{ old('l_ngaycapNhat') }}" data-mask-datetime>
        </div>
        <select name="l_trangThai" class="form-control">
            <option value="1" {{ old('l_trangThai') == 1 ? "selected" : "" }}>Khóa</option>
            <option value="2" {{ old('l_trangThai') == 2 ? "selected" : "" }}>Khả dụng</option>
        </select>
        
        <button type="submit" class="btn btn-primary">Lưu</button>
    </form>
    @endsection
    @section('custom-scripts')
    
    <!-- Các script dành cho thư viện Mặt nạ nhập liệu InputMask -->
    <script src="{{ asset('theme/adminlte/plugins/input-mask/jquery.inputmask.js') }}"></script>
    <script src="{{ asset('theme/adminlte/plugins/input-mask/jquery.inputmask.date.extensions.js') }}"></script>
    <script src="{{ asset('theme/adminlte/plugins/input-mask/jquery.inputmask.extensions.js') }}"></script>
    <script>
    $(document).ready(function(){
        
    });
    </script>
    @endsection

                        <!-- folder storage sinh ra nhờ thực hiện lệnh php artisan storage:link -->

src/laravelweb/resources/views/backend/loai/edit.blade.php
@extends('backend.layouts.master')

@section('title')
Hiệu chỉnh loại sản phẩm
@endsection

@section('custom-css')
<!-- Các css dành cho thư viện bootstrap-fileinput -->
<link href="{{ asset('vendor/bootstrap-fileinput/css/fileinput.css') }}" media="all" rel="stylesheet" type="text/css"/>
<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.5.0/css/all.css" crossorigin="anonymous">
<link href="{{ asset('vendor/bootstrap-fileinput/themes/explorer-fas/theme.css') }}" media="all" rel="stylesheet" type="text/css"/>
@endsection

@section('main-content')
@if ($errors->any())
    <div class="alert alert-danger">
        <ul>
            @foreach ($errors->all() as $error)
                <li>{{ $error }}</li>
            @endforeach
        </ul>
    </div>
@endif

<form method="post" action="{{ route('danhsachloai.update', ['id' => $l->l_ma]) }}">
    <input type="hidden" name="_method" value="PUT" />
    {{ csrf_field() }}
    <div class="form-group">
        <label for="l_ma">Loại sản phẩm</label>
        <input type="text" class="form-control" id="l_ma" name="l_ma" value="{{ $l->l_ma }}" readonly>

    </div>
    <div class="form-group">
        <label for="l_ten">Tên loại sản phẩm</label>
        <input type="text" class="form-control" id="l_ten" name="l_ten" value="{{ old('l_ten', $l->l_ten) }}">
    </div>
    
    <div class="form-group">
        <label for="l_ngaytaoMoi">Ngày tạo mới</label>
        <input type="text" class="form-control" id="l_ngaytaoMoi" name="l_ngaytaoMoi" value="{{ old('l_ngaytaoMoi', $l->l_ngaytaoMoi) }}" data-mask-datetime>
    </div>
    <div class="form-group">
        <label for="l_ngaycapNhat">Ngày cập nhật</label>
        <input type="text" class="form-control" id="l_ngaycapNhat" name="sp_capNhat" value="{{ old('l_ngaycapNhat', $l->l_ngaycapNhat) }}" data-mask-datetime>
    </div>
    <select name="l_trangThai">
        <option value="1" {{ old('l_trangThai', $l->l_trangThai) == 1 ? "selected" : "" }}>Khoa</option>
        <option value="2" {{ old('l_trangThai', $l->l_trangThai) == 2 ? "selected" : "" }}>Kha dung</option>
    </select>

    <button type="submit" class="btn btn-primary">Lưu</button>
</form>
@endsection

@section('custom-scripts')
<!-- Các script dành cho thư viện bootstrap-fileinput -->
<script src="{{ asset('vendor/bootstrap-fileinput/js/plugins/sortable.js') }}" type="text/javascript"></script>
<script src="{{ asset('vendor/bootstrap-fileinput/js/fileinput.js') }}" type="text/javascript"></script>
<script src="{{ asset('vendor/bootstrap-fileinput/js/locales/fr.js') }}" type="text/javascript"></script>
<script src="{{ asset('vendor/bootstrap-fileinput/themes/fas/theme.js') }}" type="text/javascript"></script>
<script src="{{ asset('vendor/bootstrap-fileinput/themes/explorer-fas/theme.js') }}" type="text/javascript"></script>


<!-- Các script dành cho thư viện Mặt nạ nhập liệu InputMask -->
<script src="{{ asset('theme/adminlte/plugins/input-mask/jquery.inputmask.js') }}"></script>
<script src="{{ asset('theme/adminlte/plugins/input-mask/jquery.inputmask.date.extensions.js') }}"></script>
<script src="{{ asset('theme/adminlte/plugins/input-mask/jquery.inputmask.extensions.js') }}"></script>

<script>
$(document).ready(function(){
    
});
</script>

@endsection

src/laravelweb/resources/views/backend/loai/index.blade.php
{{-- View này sẽ kế thừa giao diện từ `backend.layouts.master` --}}
    @extends('backend.layouts.master')
    {{-- Thay thế nội dung vào Placeholder `title` của view `backend.layouts.master` --}}

    @section('title')
    Danh sách loại sản phẩm
    @endsection
    
    {{-- Thay thế nội dung vào Placeholder `main-content` của view `backend.layouts.master` --}}
    @section('main-content')
    
   
    <div class="flash-message">
        @foreach (['danger', 'warning', 'success', 'info'] as $msg)
          @if(Session::has('alert-' . $msg))
          <p class="alert alert-{{ $msg }}">{{ Session::get('alert-' . $msg) }} <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a></p>
          @endif
        @endforeach
    </div>
    <!-- Tạo nút Thêm mới sản phẩm 
    - Theo quy ước, các route đã được đăng ký trong file `web.php` đều phải được đặt tên để dễ dàng bảo trì code sau này.
    - Đường dẫn URL là đường dẫn được tạo ra bằng route có tên `danhsachsanpham.create`
    - Sẽ có dạng http://tenmiencuaban.com/admin/danhsachsanpham/create
    -->
    
@if(Auth::check())
    @if(auth()->user()->can('l_them')) 
    <a href="{{ route('danhsachloai.create') }}" class="btn btn-primary" style="font-family: Tohamo; font-size: 18px;">Thêm mới loại sản phẩm</a>
    @endif
@endif  
    <br><br>
    <!-- Tạo table hiển thị danh sách các sản phẩm -->
    <table class="table table-bordered">
        <thead>
            <tr>
                <th>STT</th>
                <th>Mã</th>
                <th>Tên</th>
                <th>Ngày tạo mới</th>
                <th>Ngày cập nhật</th>
                <th>Trạng thái</th>
                <th>Sửa-Xóa</th>
            </tr>
        </thead>
        <tbody>
            <!-- Sử dụng vòng lặp foreach để duyệt qua các sản phẩm 
            - Biến $danhsachsanpham là biến được truyền qua từ action `index()` trong controller SanPhamController.
            -->
            <?php
             $stt = 1;
            ?>

            @foreach($danhsachloai as $l)
                <tr>
                    <td>{{ $loop->index + 1 }}</td>

                    <td>{{ $l->l_ma }}</td>
                    <td>{{ $l->l_ten }}</td>
                    <td>{{ $l->l_ngaytaoMoi }}</td>
                    <td>{{ $l->l_ngaycapNhat }}</td>
                    @if($l->l_trangThai == 1 )
                        <td>Khóa</td>
                    @else
                        <td>Khả dụng</td>
                    @endif
                       <td>
                       @if(Auth::check())
                            @if(auth()->user()->can('l_sua')) 
                            <a href="{{ route('danhsachloai.edit', ['id' => $l->l_ma]) }}" class="btn btn-primary pull-left">Sửa</a>
                            @endif
                        @endif
                        
                        <!-- Tạo nút Xóa sản phẩm 
                        - Theo quy ước, các route đã được đăng ký trong file `web.php` đều phải được đặt tên để dễ dàng bảo trì code sau này.
                        - Đường dẫn URL là đường dẫn được tạo ra bằng route có tên `danhsachsanpham.destroy`
                        - Route `danhsachsanpham.destroy` cần truyền vào 1 tham số {id}. Giá trị cần truyền là {id} của sản phẩm người dùng cần xóa.
                        - Các tham số cần truyền vào hàm route() là 1 array[]
                        - Sẽ có dạng http://tenmiencuaban.com/admin/danhsachsanpham/{id}
                        -->
                        @if(Auth::check())
                            @if(auth()->user()->can('l_xoa')) 
                                <form method="post" action="{{ route('danhsachloai.destroy', ['id' => $l->l_ma]) }}" class="pull-left">
                                    <!-- Khi gởi Request Xóa dữ liệu, Laravel Framework mặc định chỉ chấp nhận thực thi nếu có gởi kèm field `_method=DELETE` -->
                                    <input type="hidden" name="_method" value="DELETE" />
                                    <!-- Khi gởi bất kỳ Request POST, Laravel Framework mặc định cần có token để chống lỗi bảo mật CSRF 
                                    - Bạn có thể tắt đi, nhưng lời khuyên là không nên tắt chế độ bảo mật CSRF đi.
                                    - Thay vào đó, sử dụng hàm `csrf_field()` để tự sinh ra 1 input có token dành riêng cho CSRF
                                    -->
                                    {{ csrf_field() }}
                                    <button type="submit" class="btn btn-danger">Xóa</button>
                                </form>
                            @endif
                        @endif
                    </td>
                </tr>
                
                <?php
                $stt++;
                ?>

            @endforeach
        </tbody>
    </table>

    {{ $danhsachloai->links() }}

    @endsection