src/laravelweb/routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
use App\NhanVien;

Route::get('/', function () {
    return view('welcome');
});

//Tạo route cho phép chuyển đổi ngôn ngữ
Route::get('setLocale/{locale}', function ($locale) {
    if (in_array($locale, Config::get('app.locales'))) {
      Session::put('locale', $locale);
    }
    return redirect()->back();
})->name('app.setLocale');


// route Danh mục Sản phẩm
Route::get('/admin/danhsachsanpham/index', 'SanPhamController@index')->name('danhsachsanpham.index');
Route::get('/admin/danhsachsanpham/create', 'SanPhamController@create')->name('danhsachsanpham.create');

Route::get('/admin/danhsachsanpham/print', 'SanPhamController@print')->name('danhsachsanpham.print');
Route::get('/admin/danhsachsanpham/excel', 'SanPhamController@excel')->name('danhsachsanpham.excel');

Route::resource('/admin/danhsachsanpham', 'SanPhamController');

Route::get('/admin/danhsachsanpham', 'SanPhamController@index')
        ->middleware('auth')
        ->name('backend.sanpham.index');

// route Danh mục Loại

Route::resource('/admin/danhsachloai', 'LoaiController');
//cap quyen
Route::get('/capquyen', function(){

    //user1 & user2 = ketoan
    $user1 = NhanVien::find(1);
    $user1->givePermissionTo('sp_xem');
    $user1->givePermissionTo('sp_print');
    $user1->givePermissionTo('sp_excel');

    $user1->givePermissionTo('l_xem');


    $user2 = Nhanvien::find(2);
    $user2->givePermissionTo('sp_xem');
    $user2->givePermissionTo('sp_print');
    $user2->givePermissionTo('sp_excel');

    $user2->givePermissionTo('l_xem');


    //user3 & user4 = thukho
    $user3 = Nhanvien::find(3);
    $user3->givePermissionTo('kho_xem');
    $user3->givePermissionTo('kho_them');
    $user3->givePermissionTo('kho_sua');
    $user3->givePermissionTo('kho_xoa');

    $user4 = Nhanvien::find(3);
    $user4->givePermissionTo('kho_xem');
    $user4->givePermissionTo('kho_them');
    $user4->givePermissionTo('kho_sua');
    $user4->givePermissionTo('kho_xoa');

    //user100 = admin
    $user100 = Nhanvien::find(100);
    $user100->givePermissionTo('sp_xem');
    $user100->givePermissionTo('sp_them');
    $user100->givePermissionTo('sp_sua');
    $user100->givePermissionTo('sp_xoa');
    $user100->givePermissionTo('sp_excel');
    $user100->givePermissionTo('sp_print');

    $user100->givePermissionTo('l_xem');
    $user100->givePermissionTo('l_them');
    $user100->givePermissionTo('l_sua');
    $user100->givePermissionTo('l_xoa');
    
    return 'cap quyen okey';
});

Auth::routes();
//sua
//Route::get('/login', 'HomeController@index')->name('login');
//Route::get('/login', 'Backend\BackendController')->name('login');


Route::get('/home', 'HomeController@index')->name('home');

Route::post('/admin/activate/{nv_ma}', 'Backend\BackendController@activate')->name('activate');

//Thực hiện tạo giao diện trang chủ Frontend
Route::get('/', 'Frontend\FrontendController@index')->name('frontend.home');

//Thực hiện tạo giao diện trang Giới thiệu (about)
Route::get('/gioi-thieu', 'Frontend\FrontendController@about')->name('frontend.about');

//Thực hiện tạo giao diện trang Liên hệ (contact)
Route::get('/lien-he', 'Frontend\FrontendController@contact')->name('frontend.contact');

//tạo route sendMailContactForm
Route::post('/lien-he/goi-loi-nhan', 'Frontend\FrontendController@sendMailContactForm')->name('frontend.contact.sendMailContactForm');

//Tạo trang danh sách Sản phẩm (product)
Route::get('/san-pham', 'Frontend\FrontendController@product')->name('frontend.product');

//Tạo trang Chi tiết Sản phẩm (product-detail)
Route::get('/san-pham/{id}', 'FrontendController@productDetail')->name('frontend.productDetail');

//Tạo trang thanh toán (checkout)
Route::get('/gio-hang', 'Frontend\FrontendController@cart')->name('frontend.cart');

//Tạo đơn hàng và gởi mail xác nhận
Route::get('/gio-hang', 'Frontend\FrontendController@cart')->name('frontend.cart');
Route::post('/dat-hang', 'Frontend\FrontendController@order')->name('frontend.order');
Route::get('/dat-hang/hoan-tat', 'Frontend\FrontendController@orderFinish')->name('frontend.orderFinish');

src/laravelweb/resources/views/backend/layouts/partials/error-message.blade.php
    <!-- DIV hiển thị thông báo lỗi start -->
    @if ($errors->any())
    <div class="alert alert-danger">
        <ul>
            @foreach ($errors->all() as $error)
            <li>{{ $error }}</li>
            @endforeach
        </ul>
    </div>
    @endif
    <!-- DIV hiển thị thông báo lỗi end -->

src/laravelweb/resources/views/backend/layouts/partials/navbar.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
    <style>
            @import 'https://fonts.googleapis.com/css?family=Raleway';

       
        header h1
        {
            color: #F2F2F2;
            font-size: 30px;
            font-weight: lighter;
            margin-bottom: 5px;
        }

        header span
        {
            color: #D8D8D8;
        }

        footer span
        {
        color: #D8D8D8;
        }

        /* div.container-fluid
        {
            font-family: Raleway;
            margin: 0 auto;
            padding: 20px 3px;
            text-align: center;
        } */

        div.container-fluid a
        {
            color: #D8D8D8;
            text-decoration: none;
            font: 15px Raleway;
            margin: 0px 10px;
            padding: 10px 10px;
            position: relative;
            z-index: 0;
            cursor: pointer;
        }

        .purple
        {
            background: #2E2E2E;
        }



    /* Top and Bottom borders come in */
        div.topBotomBordersIn a:before, div.topBotomBordersIn a:after
        {
            position: absolute;
            left: 0px;
            width: 100%;
            height: 2px;
            background: #FFF;
            content: "";
            opacity: 0;
            transition: all 0.3s;
        }

        div.topBotomBordersIn a:before
        {
            top: 0px;
            transform: translateY(-10px);
        }

        div.topBotomBordersIn a:after
        {
            bottom: 0px;
            transform: translateY(10px);
        }

        div.topBotomBordersIn a:hover:before, div.topBotomBordersIn a:hover:after
        {
            opacity: 1;
            transform: translateY(0px);
        }


    </style>
</head>
<body>
    <div class="container-fluid purple topBotomBordersIn" style="color: white; font-family: Raleway;  margin: 0 auto;
            padding: 20px 3px;
            text-align: center;">
    <a>HOME</a>
    <a>ARTICLES</a>
    <a>PORTFOLIO</a>
    <a>ABOUT</a>
    <a><span style="text-transform: uppercase;">WELCOME @if (Auth::check()) {{ auth()->user()->nv_hoTen }} @endif ^^</span> </a>
    </div>

</body>
</html>

src/laravelweb/resources/views/backend/layouts/partials/sidebar.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
    <style>
            @import url(//netdna.bootstrapcdn.com/font-awesome/4.0.3/css/font-awesome.css);
        }
        @import url(https://fonts.googleapis.com/css?family=Titillium+Web:300);
        .fa-2x {
        font-size: 2em;
        }
        .fa {
        position: relative;
        display: table-cell;
        width: 60px;
        height: 36px;
        text-align: center;
        vertical-align: middle;
        font-size:20px;
        }


        .main-menu:hover,nav.main-menu.expanded {
        width:220px;
        overflow:visible;
        }

        .main-menu {
        background:#212121;
        border-right:1px solid #e5e5e5;
        position:absolute;
        top:0;
        bottom:0;
        
        left:0;
        width:60px;
        overflow:hidden;
        -webkit-transition:width .05s linear;
        transition:width .05s linear;
        -webkit-transform:translateZ(0) scale(1,1);
        z-index:1000;
        }

        .main-menu>ul {
        margin:7px 0;
        }

        .main-menu li {
        position:relative;
        display:block;
        width:220px;
        }

        .main-menu li>a {
        position:relative;
        display:table;
        border-collapse:collapse;
        border-spacing:0;
        color:#999;
        font-family: arial;
        font-size: 14px;
        text-decoration:none;
        -webkit-transform:translateZ(0) scale(1,1);
        -webkit-transition:all .1s linear;
        transition:all .1s linear;
        
        }

        .main-menu .nav-icon {
        position:relative;
        display:table-cell;
        width:60px;
        height:36px;
        text-align:center;
        vertical-align:middle;
        font-size:18px;
        }

        .main-menu .nav-text {
        position:relative;
        display:table-cell;
        vertical-align:middle;
        width:190px;
        font-family: 'Titillium Web', sans-serif;
        }

        .main-menu>ul.logout {
        position:absolute;
        left:0;
        bottom:0;
        }

        .no-touch .scrollable.hover {
        overflow-y:hidden;
        }

        .no-touch .scrollable.hover:hover {
        overflow-y:auto;
        overflow:visible;
        }

        a:hover,a:focus {
        text-decoration:none;
        }

        nav {
        -webkit-user-select:none;
        -moz-user-select:none;
        -ms-user-select:none;
        -o-user-select:none;
        user-select:none;
        }

        nav ul,nav li {
        outline:0;
        margin:0;
        padding:0;
        }
        .main-menu li:hover>a,nav.main-menu li.active>a,.dropdown-menu>li>a:hover,.dropdown-menu>li>a:focus,.dropdown-menu>.active>a,.dropdown-menu>.active>a:hover,.dropdown-menu>.active>a:focus,.no-touch .dashboard-page nav.dashboard-menu ul li:hover a,.dashboard-page nav.dashboard-menu ul li.active a {
        color:#fff;
        background-color:#5fa2db;
        }
        .area {
        float: left;
        background: #e2e2e2;
        width: 100%;
        height: 100%;
        }
        @font-face {
        font-family: 'Titillium Web';
        font-style: normal;
        font-weight: 300;
        src: local('Titillium WebLight'), local('TitilliumWeb-Light'), url(http://themes.googleusercontent.com/static/fonts/titilliumweb/v2/anMUvcNT0H1YN4FII8wpr24bNCNEoFTpS2BTjF6FB5E.woff) format('woff');
        }

    </style>
</head>
<body>
    
    <nav class="main-menu" style="margin-top: 64px;" >
            <ul>
                <li>
                    <a href="http://justinfarrow.com">
                        <i class="fa fa-home fa-2x"></i>
                        <span class="nav-text">
                            Dashboard
                        </span>
                    </a>
                  
                </li>
               
                <li class="has-subnav">
                    <a href="{{ route('danhsachsanpham.index') }}">
                    <i class="fa fa-list fa-2x"></i>
                        <span class="nav-text">
                        Danh sách sản phẩm
                        </span>
                    </a>
                    
                </li>
                  
                <li class="has-subnav">
                    <a href="{{ route('danhsachloai.index') }}">
                       <i class="fa fa-list fa-2x"></i>
                        <span class="nav-text">
                        Danh sách loại
                        </span>
                    </a>
                    
                </li>
                
                <li>
                    <a href="#">
                        <i class="fa fa-bar-chart-o fa-2x"></i>
                        <span class="nav-text">
                            Graphs and Statistics
                        </span>
                    </a>
                </li>
                <li>
                    <a href="#">
                        <i class="fa fa-font fa-2x"></i>
                        <span class="nav-text">
                           Quotes
                        </span>
                    </a>
                </li>
                <li>
                   <a href="#">
                       <i class="fa fa-table fa-2x"></i>
                        <span class="nav-text">
                            Tables
                        </span>
                    </a>
                </li>
                <li>
                   <a href="#">
                        <i class="fa fa-map-marker fa-2x"></i>
                        <span class="nav-text">
                            Maps
                        </span>
                    </a>
                </li>
                
            </ul>

            <ul class="logout">
                <li>
                
                   <a href="class="nav-link href="{{ route('logout') }}"
                     onclick="event.preventDefault();
                     document.getElementById('logout-form').submit();">
                         <i class="fa fa-power-off fa-2x"></i>
                        <span class="nav-text">
                            Logout
                        </span>
                    <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                        {{ csrf_field() }}
                    </form>

                    </a>
                    
                </li>  
            </ul>
        </nav>
  </body>
</html>